In [1]:
import tensorflow
from tensorflow.keras.preprocessing.text import one_hot

In [2]:
sent = ['the glass of milk',
        'the glass of juice',
        'the cup of tea',
        'I am a good boy',
        'I am a good developer',
        'understand the meaning of words',
        'your videos are good']

In [3]:
sent

['the glass of milk',
 'the glass of juice',
 'the cup of tea',
 'I am a good boy',
 'I am a good developer',
 'understand the meaning of words',
 'your videos are good']

In [4]:
# Define the vocabulary size
voc_size = 10000

In [5]:
# One Hot Representation for every word
one_hot_representation = [one_hot(words, voc_size)for words in sent]
one_hot_representation

[[9960, 6534, 4769, 7978],
 [9960, 6534, 4769, 2291],
 [9960, 5105, 4769, 8065],
 [3390, 9399, 3186, 5075, 3508],
 [3390, 9399, 3186, 5075, 6922],
 [879, 9960, 9532, 4769, 7123],
 [6310, 8676, 517, 5075]]

In [7]:
# Word Embedding Representation
from tensorflow.keras.layers import Embedding
from tensorflow.keras.utils import pad_sequences
from tensorflow.keras.models import Sequential

In [8]:
import numpy as np

In [9]:
# The number of input should be same but our dataset has variable word length
sent_length = 8
embedded_docs = pad_sequences(one_hot_representation, padding = 'pre', maxlen= sent_length)
print(embedded_docs)

[[   0    0    0    0 9960 6534 4769 7978]
 [   0    0    0    0 9960 6534 4769 2291]
 [   0    0    0    0 9960 5105 4769 8065]
 [   0    0    0 3390 9399 3186 5075 3508]
 [   0    0    0 3390 9399 3186 5075 6922]
 [   0    0    0  879 9960 9532 4769 7123]
 [   0    0    0    0 6310 8676  517 5075]]


In [11]:
# feature representation
dim= 10

In [12]:
model = Sequential()
model.add(Embedding(voc_size, dim, input_length= sent_length))
model.compile('adam', 'mse')

c:\Users\acer\OneDrive\Desktop\RNN-project\.venv\Lib\site-packages\keras\src\layers\core\embedding.py:103: UserWarning: Argument `input_length` is deprecated. Just remove it.
  warnings.warn(
